---
title: "ACS data on counties surrounding Atlanta"
output:
  html_document:
    toc: true
    fig_caption: true
---

```{r}
library(tidyverse)
library(tidycensus)
library(lubridate)
library(zoo)
```

```{r}
# variables to collect:
# population number
# population by race
# mediam income
# mediam rent
# median house prices
# look these variables up in the detailed tables rather than the
# data profiles!!
# Bands for gross rent as percentage of income:
# B25070_001 to _011
acs_variables <- c(
    #median_unit_value = "DP04_0089",
    median_rent = "B25064_001",
    median_rent_income_percent = "B25071_001",
    median_household_income = "B25099_001",
    median_unit_value = "B25077_001",
    #total_units = "DP04_0001",
    #occupied_rental_units = "DP04_0126",
    #occupied_owned_units = "DP04_0080",
    total_pop = "B01003_001",
    pop_white = "B02008_001",
    pop_baa = "B02009_001",
    pop_aian = "B02010_001",
    pop_asian = "B02011_001",
    pop_nhpi = "B02012_001",
    pop_other_race = "B02013_001",
    pop_foreign_born = "B05002_013"
)

counties_list_1 <- c(
    'Fulton', 'Gwinnett',
    'Cobb', 'DeKalb', 'Clayton',
    'Cherokee', 'Forsyth',
    'Henry', 'Paulding', 'Coweta',
    'Douglas', 'Fayette', 'Carroll',
    'Newton', 'Bartow', 'Walton', 
    'Rockdale'
)

counties_list_2 <- c(
    'Barrow', 'Spalding', 'Pickens', 
    'Haralson', 'Dawson', 'Butts', 
    'Meriwether', 'Morgan',
    'Pike', 'Lamar', 'Jasper', 'Heard'
)

counties_list <- c(counties_list_1, counties_list_2)

counties_list_3 <- c(
    'Fulton', 'Cobb', 'DeKalb', 
    'Douglas', 'Fayette', 'Henry', 
    'Gwinnett', 'Clayton'
)
```

```{r, eval = FALSE, include = FALSE}
v11 <- load_variables(2011, "acs5", cache = TRUE)
v17 <- load_variables(2017, "acs5", cache = TRUE)
View(v11)
View(v17)
```

```{r, warning = FALSE, message = FALSE, eval = FALSE}
years_acs1 <- lst(
    2009, 2010, 2011, 2012, 2013, 2014, 
    2015, 2016, 2017, 2018, 2019
)

years_acs5 <- lst(
    2010, 2011, 2012, 2013, 2014, 
    2015, 2016, 2017, 2018, 2019, 2020
)

df_counties_temp <- map_dfr(
    years_acs1,
    ~ get_acs(
        geography = "county",
        state = "GA",
        variables = acs_variables,
        year = .x,
        county = counties_list,
        survey = "acs5",
        geometry = FALSE
    ),
    .id = "year")

df_counties <- df_counties_temp %>%
    mutate(
        county = gsub("^(.*?),.*", "\\1", NAME)
    ) %>% select(-NAME) %>% relocate(county, .after = GEOID)

write_csv(df_counties, 'ajc-satellite/data/acs1_counties.csv')

df_tracts_temp <- map_dfr(
    years_acs5,
    ~ get_acs(
        geography = "tract",
        state = "GA",
        variables = acs_variables,
        year = .x,
        county = counties_list,
        survey = "acs5",
        geometry = FALSE
    ),
    .id = "year")

df_tracts <- df_tracts_temp %>%
    mutate(
        tract = gsub("^(.*?),.*", "\\1", NAME),
        county = gsub("^(.*?), (.*?),.*", "\\2", NAME)
    ) %>% select(-NAME) %>% relocate(tract, county, .after = GEOID)

write_csv(df_tracts, 'ajc-satellite/data/acs5_tracts.csv')
```

```{r, include = FALSE}
df <- read_csv('ajc-satellite/data/acs_demo.csv')
```

```{r}
df_ratio <- df %>% pivot_wider(
    names_from = variable, names_prefix = "var_",
    values_from = estimate
) %>% mutate(
    across(starts_with('var_pop'), ~ . / var_total_pop)
)

new_names <- tibble(
    variable = c(
        "var_pop_white", "var_pop_baa",
        "var_pop_foreign_born", "var_pop_asian"
    ),
    demographic = c(
        "White", "Black or African American",
        "Foreign Born", "Asian"
    ))

df_rents <- df_ratio %>%
    mutate(year = ymd(year, truncated = 2L)) %>%
    select(year, NAME, var_median_rent_income_percent)

df_ratio %>%
    mutate(year = ymd(year, truncated = 2L)) %>%
    select(year, NAME, var_pop_white, var_pop_baa,
    var_pop_foreign_born, var_pop_asian) %>%
    group_by(NAME) %>%
    mutate(across(starts_with('var'), 
        function(x) c(NA, diff(x)))) %>% ungroup() %>%
    pivot_longer(
        cols = starts_with('var'),
        names_to = "variable",
        values_to = "estimate"
    ) %>%
    left_join(new_names) %>%
    ggplot(aes(x = year, y = estimate, col = demographic)) +
    geom_line() + facet_wrap(~ NAME) +
    labs(
        x = "Year", 
        y = "Absolute Changes in Proportion of Population",
        col = "Demographic"
    ) +
    theme(legend.position = "bottom")
```

```{r}
# density (population density)
# home/rental prices
# infrastructure

# plot income against percentage spent on rent
# (need to adjust income for inflation)

# look for income by race 
df2 <- df %>% mutate(
    year = ymd(year, truncated = 2L),
    ) %>%
    filter(variable == 'median_rent_income_percent') %>%
    select(year, NAME, estimate) %>%
    pivot_wider(
        names_from = NAME,
        values_from = estimate
    ) %>%
    mutate_if(
        is.numeric, zoo
    ) %>% mutate(
        across(-year, function(x) 
        diff(zoo(x), na.pad = TRUE, arithmetic = FALSE)),
        across(-year, as.numeric)
    ) %>%
    pivot_longer(
        cols = ends_with('County'),
        names_to = "county",
        values_to = "est_diff"
    )

df2 %>% ggplot(aes(x = year, y = est_diff, col = county)) +
    facet_wrap( ~ county) +
    geom_line()
```
